name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Grant Gradle permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test --no-daemon
        env:
          JAVA_OPTS: "-Xmx2g -Xms512m"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/islam24-backend:latest

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Pull and restart container
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/islam24-backend:latest

          docker stop islam24-backend || true
          docker rm islam24-backend || true

          docker run -d \
            --name islam24-backend \
            --network custom_bridge \
            --ip 172.25.0.13 \
            --env-file /home/envs/islam24-backend.env \
            -p 9393:9393 \
            --restart unless-stopped \
            ${{ secrets.DOCKERHUB_USERNAME }}/islam24-backend:latest

          sleep 5
          docker ps | grep islam24-backend
